In [2]:
#Pistes concernant les causes de la faim
#Feuille de calcul :

In [3]:
#-*- coding: utf-8 -*

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from random import randint, seed

In [4]:
#Table population
pop = pd.read_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/FAOSTAT_data_10-25-2018-1.csv", encoding='utf-8')

pop = pop[pop['Produit'] == 'Population']
pop = pop.pivot_table(index=['Pays'], columns='Produit', values='Valeur')
pop['Population'] = pop['Population']*1000



#On va ici calculer le ratio d'importations et d'exportations / Production : 

data = pd.read_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/causes_faim/imports_exports.csv", encoding='utf-8')

data = data.pivot_table(index = ['Pays', 'Produit'], columns = 'Élément', values = 'Valeur')
data.columns = ['Exports', 'Imports', 'Prod']
data = data.reset_index().groupby('Pays')

data = data.sum()

data_ratio = data

data_ratio['ratio exports/prod'] = data_ratio['Exports']/data_ratio['Prod']*100
data_ratio['ratio imports/prod'] = data_ratio['Imports']/data_ratio['Prod']*100

data_ratio = data_ratio.sort_values('ratio exports/prod', ascending = False)
data_ratio = data_ratio.round(1)[0:20]


#On merge les deux tables pour pouvoir calculer la disponibilité intérieure par habitant pour chaque pays : 

data_pop = pd.merge(data, pop, left_on = 'Pays', right_on = 'Pays')

#Et on calcule le ratio prod/population (En tonnes par habitant) : 
prod_pop = data_pop
prod_pop['ratio prod/pop'] = prod_pop['Prod']/prod_pop['Population']*1000
prod_pop = prod_pop.sort_values('ratio prod/pop', ascending=True)
prod_pop = prod_pop.round(1)[0:20]

In [5]:
#Les ratios : 
data_ratio

,Exports,Imports,Prod,ratio exports/prod,ratio imports/prod
Pays,,,,,
Chine - RAS de Hong-Kong,3604.0,9510.0,470.0,766.8,2023.4
Bermudes,24.0,77.0,6.0,400.0,1283.3
Émirats arabes unis,4343.0,15327.0,1192.0,364.3,1285.8
Djibouti,113.0,1628.0,76.0,148.7,2142.1
Luxembourg,821.0,1076.0,593.0,138.4,181.5
Pays-Bas,52179.0,52910.0,41636.0,125.3,127.1
Belgique,30345.0,35276.0,24496.0,123.9,144.0
Oman,1217.0,3464.0,1169.0,104.1,296.3
Islande,1440.0,258.0,1657.0,86.9,15.6
Nouvelle-Zélande,22805.0,2072.0,26896.0,84.8,7.7
Koweït,467.0,3690.0,636.0,73.4,580.2
Uruguay,8179.0,1213.0,11587.0,70.6,10.5
Lettonie,3001.0,1747.0,4413.0,68.0,39.6
Malaisie,25026.0,18052.0,37033.0,67.6,48.7
Slovénie,1192.0,1915.0,1854.0,64.3,103.3
Lituanie,5963.0,3060.0,9761.0,61.1,31.3
Bulgarie,9466.0,2293.0,15564.0,60.8,14.7
Irlande,6828.0,6254.0,11501.0,59.4,54.4
Estonie,1421.0,929.0,2530.0,56.2,36.7
Arabie saoudite,4707.0,27726.0,8878.0,53.0,312.3

In [6]:
prod_pop

,Exports,Imports,Prod,ratio exports/prod,ratio imports/prod,Population,ratio prod/pop
Pays,,,,,,,
Chine - RAS de Macao,2.0,367.0,16.0,12.5,2293.8,566000,0.0
Chine - RAS de Hong-Kong,3604.0,9510.0,470.0,766.8,2023.4,7204000,0.1
Djibouti,113.0,1628.0,76.0,148.7,2142.1,873000,0.1
Bermudes,24.0,77.0,6.0,400.0,1283.3,65000,0.1
Émirats arabes unis,4343.0,15327.0,1192.0,364.3,1285.8,9346000,0.1
Brunéi Darussalam,11.0,244.0,60.0,18.3,406.7,418000,0.1
Yémen,719.0,6786.0,4125.0,17.4,164.5,24407000,0.2
Koweït,467.0,3690.0,636.0,73.4,580.2,3369000,0.2
Lesotho,32.0,467.0,418.0,7.7,111.7,2074000,0.2
Trinité-et-Tobago,95.0,898.0,275.0,34.5,326.5,1341000,0.2
Antigua-et-Barbuda,0.0,63.0,20.0,0.0,315.0,90000,0.2
Gambie,46.0,419.0,457.0,10.1,91.7,1849000,0.2
Botswana,68.0,958.0,502.0,13.5,190.8,2021000,0.2
Mauritanie,172.0,1293.0,1151.0,14.9,112.3,3890000,0.3
Nouvelle-Calédonie,5.0,201.0,78.0,6.4,257.7,256000,0.3
Arabie saoudite,4707.0,27726.0,8878.0,53.0,312.3,28829000,0.3
Oman,1217.0,3464.0,1169.0,104.1,296.3,3632000,0.3
Timor-Leste,23.0,100.0,371.0,6.2,27.0,1133000,0.3
Sénégal,548.0,2813.0,4972.0,11.0,56.6,14133000,0.4
Libéria,34.0,470.0,1533.0,2.2,30.7,4294000,0.4

In [7]:
#Df sur les pertes et la nourriture pour chaque pays :
data_pn = pd.read_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/causes_faim/pertes_nourritures.csv", encoding='utf-8')

data_pn = data_pn.pivot_table(index=['Pays'], columns=['Élément'], values='Valeur')

#On met aux bonnes unités ; Population en population totale et nourritures, pertes, en tonnes
data_pn['Population totale'] = data_pn['Population totale']*1000
data_pn['Nourriture'] = (data_pn['Nourriture']*1000).round(0)
data_pn['Pertes'] = (data_pn['Pertes']*1000).round(0)

#On calcule ensuite la population totale : 
pop_tot = data_pn['Population totale'].drop(index='Chine, continentale').sum()

#On calcule ensuite la somme de pertes totale (en tonnes) : 
pertes_tot = data_pn['Pertes'].drop(index='Chine, continentale').sum()

#On calcule la somme de nourriture totale (en tonnes) : 
nourriture_tot = data_pn['Nourriture'].drop(index='Chine, continentale').sum()

#Puis enfin le ratio perte/nourriture
ratio_pn = (pertes_tot/nourriture_tot*100).round(0)

In [8]:
print('La perte totale (en tonnes) est de : {} au niveau mondial'.format(pertes_tot))

print('------------------------')

print('La nourriture totale (en tonnes) est de : {} au niveau mondial'.format(nourriture_tot))

print('------------------------')

print('La ratio pertes/nourriture est de : {} %'.format(ratio_pn))
print('Ce dernier ratio ne prend pas en compte les pertes des ménages directement, le chiffre est donc bien plus élevé en réalité.')

La perte totale (en tonnes) est de : 13191996.0 au niveau mondial
------------------------
La nourriture totale (en tonnes) est de : 57031521.0 au niveau mondial
------------------------
La ratio pertes/nourriture est de : 23.0 %
Ce dernier ratio ne prend pas en compte les pertes des ménages directement, le chiffre est donc bien plus élevé en réalité.

In [15]:
data_pn['Pertes'] = data_pn['Pertes'].drop(index ='Chine, continentale')
data_pn["Pertes"].sort_values(ascending = False)

Pays
Brésil                             1997737.0
Chine                              1771725.0
Inde                               1434103.0
Nigéria                             661800.0
Indonésie                           451069.0
Turquie                             354000.0
Ghana                               275630.0
Mexique                             243794.0
Viet Nam                            240821.0
Égypte                              223765.0
Pakistan                            210607.0
Angola                              208652.0
Thaïlande                           198241.0
États-Unis d'Amérique               188474.0
Iran (République islamique d')      181667.0
Fédération de Russie                161194.0
Ukraine                             147786.0
Bangladesh                          131613.0
Algérie                             125100.0
Cameroun                            124406.0
France                              120778.0
Malawi                              115619.0
Népal                               105500.0
Philippines                         103607.0
Allemagne                           102189.0
Cambodge                             99200.0
Argentine                            95189.0
République-Unie de Tanzanie          89889.0
Sierra Leone                         87640.0
Éthiopie                             83556.0
                                     ...
Suriname                              1571.0
Belize                                1500.0
Samoa                                 1333.0
Dominique                              952.0
Djibouti                               909.0
Cabo Verde                             875.0
Maurice                                789.0
Timor-Leste                            778.0
Malte                                  739.0
Fidji                                  722.0
Sao Tomé-et-Principe                   714.0
Trinité-et-Tobago                      679.0
Luxembourg                             611.0
Sainte-Lucie                           480.0
Îles Salomon                           429.0
Chine - RAS de Macao                   333.0
Saint-Vincent-et-les Grenadines        312.0
Brunéi Darussalam                      308.0
Nouvelle-Calédonie                     158.0
Polynésie française                    150.0
Bahamas                                143.0
Barbade                                118.0
Grenade                                111.0
Islande                                  0.0
Maldives                                 0.0
Antigua-et-Barbuda                       0.0
Bermudes                                 0.0
Kiribati                                 0.0
Saint-Kitts-et-Nevis                     0.0
Chine, continentale                      NaN
Name: Pertes, Length: 175, dtype: float64

Élément,Nourriture,Pertes,Population totale
Pays,,,
Afghanistan,198796.0,63056.0,30552000.0
Afrique du Sud,346651.0,68531.0,52776000.0
Albanie,44564.0,12000.0,3173000.0
Algérie,386939.0,125100.0,39208000.0
Allemagne,954675.0,102189.0,82727000.0
Angola,203500.0,208652.0,21472000.0
Antigua-et-Barbuda,690.0,0.0,90000.0
Arabie saoudite,204045.0,34667.0,28829000.0
Argentine,406638.0,95189.0,41446000.0
Arménie,37551.0,12667.0,2977000.0
Australie,271457.0,20000.0,23343000.0
Autriche,106882.0,14806.0,8495000.0
Azerbaïdjan,104776.0,12889.0,9413000.0
Bahamas,3671.0,143.0,377000.0
Bangladesh,656230.0,131613.0,156595000.0
Barbade,2417.0,118.0,285000.0
Belgique,135780.0,21692.0,11104000.0
Belize,2671.0,1500.0,332000.0
Bermudes,699.0,0.0,65000.0
Bolivie (État plurinational de),67232.0,15000.0,10671000.0
Bosnie-Herzégovine,45429.0,10423.0,3829000.0
Botswana,12648.0,2833.0,2021000.0
Brunéi Darussalam,3035.0,308.0,418000.0
Brésil,1795931.0,1997737.0,200362000.0
Bulgarie,63888.0,29459.0,7223000.0
Burkina Faso,112440.0,27957.0,16935000.0
Bélarus,111808.0,21148.0,9357000.0
Bénin,73365.0,54280.0,10323000.0
Cabo Verde,4141.0,875.0,499000.0
Cambodge,73059.0,99200.0,15135000.0
...,...,...,...
Sri Lanka,119407.0,18923.0,21273000.0
Suisse,92907.0,5885.0,8078000.0
Suriname,4145.0,1571.0,539000.0
Suède,115976.0,11148.0,9571000.0
Sénégal,61253.0,13917.0,14133000.0
Tadjikistan,79093.0,22167.0,8208000.0
Tchad,61149.0,20864.0,12825000.0
Tchéquie (la),117253.0,9679.0,10702000.0
Thaïlande,456779.0,198241.0,67011000.0
Timor-Leste,7351.0,778.0,1133000.0
Togo,37929.0,19833.0,6817000.0
Trinité-et-Tobago,11100.0,679.0,1341000.0
Tunisie,108706.0,26296.0,10997000.0
Turkménistan,73771.0,13600.0,5240000.0
Turquie,895691.0,354000.0,74933000.0
Ukraine,523553.0,147786.0,45239000.0
Uruguay,33225.0,17129.0,3407000.0
Vanuatu,2629.0,3000.0,253000.0
Venezuela (République bolivarienne du),228195.0,29750.0,30405000.0
Viet Nam,731944.0,240821.0,91680000.0
Yémen,107788.0,10760.0,24407000.0
Zambie,58483.0,10522.0,14539000.0
Zimbabwe,54736.0,7231.0,14150000.0
l'ex-République yougoslave de Macédoine,21762.0,7667.0,2107000.0
Égypte,766942.0,223765.0,82056000.0
Émirats arabes unis,89699.0,21364.0,9346000.0
Équateur,100871.0,17675.0,15738000.0
États-Unis d'Amérique,3731267.0,188474.0,320051000.0
Éthiopie,383460.0,83556.0,94101000.0
Îles Salomon,5099.0,429.0,561000.0