In [1]:
#-*- coding: utf-8 -*

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pop = pd.read_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/pop_q15.csv", encoding='utf-8')

pop = pop.drop(columns=['Code Domaine', 'Domaine', 'Code Élément', 'Code Produit','Code Année', 'Symbole', 'Description du Symbole'])
pop = pop.pivot_table(pop, index=['Pays', 'Code Pays', 'Année'],
                                 columns=['Élément'])
pop.columns = ['population']
pop = pop['population']*1000

pop = pop.reset_index()

pop.columns=['pays', 'code_pays', 'annee', 'population']

pop

                                        pays  code_pays  annee  population
0                                Afghanistan          2   2012    29825000
1                                Afghanistan          2   2013    30552000
2                             Afrique du Sud        202   2012    52386000
3                             Afrique du Sud        202   2013    52776000
4                                    Albanie          3   2012     3162000
5                                    Albanie          3   2013     3173000
6                                    Algérie          4   2012    38482000
7                                    Algérie          4   2013    39208000
8                                  Allemagne         79   2012    82800000
9                                  Allemagne         79   2013    82727000
10                                    Angola          7   2012    20821000
11                                    Angola          7   2013    21472000
12                        Antigua-et-Barbuda          8   2012       89000
13                        Antigua-et-Barbuda          8   2013       90000
14                           Arabie saoudite        194   2012    28288000
15                           Arabie saoudite        194   2013    28829000
16                                 Argentine          9   2012    41087000
17                                 Argentine          9   2013    41446000
18                                   Arménie          1   2012     2969000
19                                   Arménie          1   2013     2977000
20                                 Australie         10   2012    23050000
21                                 Australie         10   2013    23343000
22                                  Autriche         11   2012     8464000
23                                  Autriche         11   2013     8495000
24                               Azerbaïdjan         52   2012     9309000
25                               Azerbaïdjan         52   2013     9413000
26                                   Bahamas         12   2012      372000
27                                   Bahamas         12   2013      377000
28                                Bangladesh         16   2012   154695000
29                                Bangladesh         16   2013   156595000
..                                       ...        ...    ...         ...
320                                  Ukraine        230   2012    45530000
321                                  Ukraine        230   2013    45239000
322                                  Uruguay        234   2012     3395000
323                                  Uruguay        234   2013     3407000
324                                  Vanuatu        155   2012      247000
325                                  Vanuatu        155   2013      253000
326   Venezuela (République bolivarienne du)        236   2012    29955000
327   Venezuela (République bolivarienne du)        236   2013    30405000
328                                 Viet Nam        237   2012    90796000
329                                 Viet Nam        237   2013    91680000
330                                    Yémen        249   2012    23852000
331                                    Yémen        249   2013    24407000
332                                   Zambie        251   2012    14075000
333                                   Zambie        251   2013    14539000
334                                 Zimbabwe        181   2012    13724000
335                                 Zimbabwe        181   2013    14150000
336  l'ex-République yougoslave de Macédoine        154   2012     2106000
337  l'ex-République yougoslave de Macédoine        154   2013     2107000
338                                   Égypte         59   2012    80722000
339                                   Égypte         59   2013    82056000
340                      Émirats arabes unis        225   2012     9206000
341                      Émirats arabes unis        225   2013     9346000
342                                 Équateur         58   2012    15492000
343                                 Équateur         58   2013    15738000
344                    États-Unis d'Amérique        231   2012   317505000
345                    États-Unis d'Amérique        231   2013   320051000
346                                 Éthiopie        238   2012    91729000
347                                 Éthiopie        238   2013    94101000
348                             Îles Salomon         25   2012      550000
349                             Îles Salomon         25   2013      561000

[350 rows x 4 columns]

In [3]:
"""La clé primaire serait soit Code pays-Année, soit Pays-Année ; Aucun pays ne se répète deux fois pour une année donnée."""

'La clé primaire serait soit Code pays-Année, soit Pays-Année ; Aucun pays ne se répète deux fois pour une année donnée.'

In [4]:
pop.to_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/population.csv", index = False)

In [5]:
"""Question 16"""

'Question 16'

In [6]:
veg = pd.read_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/vege_q16.csv", encoding='utf-8')

ani = pd.read_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/ani_q16.csv", encoding='utf-8')


# Ajout de la variable origin

ani["Origine"] = "animal"

veg["Origine"] = "vegetal"


# On regroupe veg et ani en un unique dataframe, via une union

temp_df = ani.append(veg)


# On supprime les anciens df ani et veg

del ani, veg

#On renomme les colonnes avec accents : 
#temp_df.rename(index=str, columns = {'Année' : 'Annee', 'Élément' : 'Element'})


# Transformation de temp_df en table pivot

data_q16 = temp_df.pivot_table(

    index=['Code Pays','Pays','Code Produit','Produit','Année','Origine'],

    columns = ["Élément"], values=["Valeur"])

#On renomme les colonnes comme précisé dans la consigne
data_q16.columns = ['dispo_alim_kcal_p_j', 'dispo_alim_tonnes', 'dispo_mat_gr', 'dispo_prot']

#On passe la colonne dispo_alim_tonnes en tonnes (unité de base en kg)
data_q16['dispo_alim_tonnes'] = data_q16['dispo_alim_tonnes']/1000

data_q16 = data_q16.reset_index()

data_q16.columns = ['code_pays', 'pays', 'code_produit', 'produit', 'annee', 'origine', 'dispo_alim_kcal-p-j', 'dispo_alim_tonnes', 'dispo_mat_gr', 'dispo_prot']

data_q16

,code_pays,pays,code_produit,produit,annee,origine,dispo_alim_kcal-p-j,dispo_alim_tonnes,dispo_mat_gr,dispo_prot
0,1,Arménie,2511,Blé,2012,vegetal,995.0,0.12694,3.53,29.69
1,1,Arménie,2511,Blé,2013,vegetal,1024.0,0.13060,3.60,30.52
2,1,Arménie,2513,Orge,2012,vegetal,1.0,0.00017,0.01,0.03
3,1,Arménie,2513,Orge,2013,vegetal,0.0,0.00000,0.00,0.00
4,1,Arménie,2514,Maïs,2012,vegetal,0.0,0.00003,NaN,0.01
5,1,Arménie,2514,Maïs,2013,vegetal,0.0,0.00003,NaN,0.01
6,1,Arménie,2515,Seigle,2012,vegetal,1.0,0.00015,0.01,0.03
7,1,Arménie,2515,Seigle,2013,vegetal,1.0,0.00012,0.00,0.02
8,1,Arménie,2516,Avoine,2012,vegetal,2.0,0.00032,0.03,0.08
9,1,Arménie,2516,Avoine,2013,vegetal,2.0,0.00037,0.03,0.09
10,1,Arménie,2520,"Céréales, Autres",2012,vegetal,13.0,0.00177,0.04,0.36
11,1,Arménie,2520,"Céréales, Autres",2013,vegetal,14.0,0.00196,0.04,0.39
12,1,Arménie,2531,Pommes de Terre,2012,vegetal,82.0,0.04476,0.12,1.93
13,1,Arménie,2531,Pommes de Terre,2013,vegetal,82.0,0.04510,0.12,1.94
14,1,Arménie,2542,Sucre Eq Brut,2012,vegetal,315.0,0.03376,NaN,NaN
15,1,Arménie,2542,Sucre Eq Brut,2013,vegetal,302.0,0.03303,NaN,NaN
16,1,Arménie,2543,Edulcorants Autres,2012,vegetal,25.0,0.00246,NaN,NaN
17,1,Arménie,2543,Edulcorants Autres,2013,vegetal,18.0,0.00182,NaN,NaN
18,1,Arménie,2549,Légumineuses Autres,2012,vegetal,0.0,0.00000,NaN,0.00
19,1,Arménie,2549,Légumineuses Autres,2013,vegetal,0.0,0.00000,NaN,0.00
20,1,Arménie,2551,Noix,2012,vegetal,14.0,0.00174,1.33,0.30
21,1,Arménie,2551,Noix,2013,vegetal,18.0,0.00215,1.76,0.42
22,1,Arménie,2555,Soja,2012,vegetal,0.0,0.00000,NaN,NaN
23,1,Arménie,2555,Soja,2013,vegetal,0.0,0.00000,NaN,NaN
24,1,Arménie,2556,Arachides Decortiquees,2012,vegetal,4.0,0.00022,0.31,0.16
25,1,Arménie,2556,Arachides Decortiquees,2013,vegetal,6.0,0.00040,0.55,0.29
26,1,Arménie,2558,Graines Colza/Moutarde,2012,vegetal,0.0,0.00000,0.00,0.00
27,1,Arménie,2558,Graines Colza/Moutarde,2013,vegetal,0.0,0.00000,0.00,0.00
28,1,Arménie,2560,Coco (Incl Coprah),2012,vegetal,0.0,0.00013,0.05,0.00
29,1,Arménie,2560,Coco (Incl Coprah),2013,vegetal,0.0,0.00008,0.03,0.00
...,...,...,...,...,...,...,...,...,...,...
28676,351,Chine,2745,Miel,2012,vegetal,2.0,0.00025,NaN,0.00
28677,351,Chine,2745,Miel,2013,vegetal,2.0,0.00025,NaN,0.00
28678,351,Chine,2761,Poissons Eau Douce,2012,animal,30.0,0.01596,1.09,4.76
28679,351,Chine,2761,Poissons Eau Douce,2013,animal,30.0,0.01587,1.09,4.73
28680,351,Chine,2762,Perciform,2012,animal,6.0,0.00342,0.07,1.19
28681,351,Chine,2762,Perciform,2013,animal,6.0,0.00340,0.06,1.18
28682,351,Chine,2763,Poissons Pelagiques,2012,animal,1.0,0.00039,0.04,0.13
28683,351,Chine,2763,Poissons Pelagiques,2013,animal,1.0,0.00039,0.04,0.13
28684,351,Chine,2764,"Poissons Marins, Autres",2012,animal,3.0,0.00145,0.12,0.50
28685,351,Chine,2764,"Poissons Marins, Autres",2013,animal,3.0,0.00144,0.12,0.49
28686,351,Chine,2765,Crustacés,2012,animal,5.0,0.00393,0.05,0.98
28687,351,Chine,2765,Crustacés,2013,animal,5.0,0.00390,0.05,0.98
28688,351,Chine,2766,Cephalopodes,2012,animal,2.0,0.00083,0.02,0.32
28689,351,Chine,2766,Cephalopodes,2013,animal,2.0,0.00083,0.02,0.32
28690,351,Chine,2767,"Mollusques, Autres",2012,animal,4.0,0.00890,0.05,0.57
28691,351,Chine,2767,"Mollusques, Autres",2013,animal,4.0,0.00885,0.05,0.56
28692,351,Chine,2769,Animaux Aquatiques Autre,2012,animal,1.0,0.00068,0.00,0.07
28693,351,Chine,2769,Animaux Aquatiques Autre,2013,animal,1.0,0.00067,0.00,0.07
28694,351,Chine,2775,Plantes Aquatiques,2012,animal,9.0,0.00929,0.04,0.69
28695,351,Chine,2775,Plantes Aquatiques,2013,animal,9.0,0.00924,0.04,0.69
28696,351,Chine,2781,Huiles de Poissons,2012,animal,0.0,0.00000,0.00,0.00
28697,351,Chine,2781,Huiles de Poissons,2013,animal,0.0,0.00000,0.00,0.00
28698,351,Chine,2782,Huiles de Foie de Poisso,2012,animal,0.0,0.00000,0.00,0.00
28699,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.00000,0.00,0.00
28700,351,Chine,2805,Riz (Eq Blanchi),2012,vegetal,801.0,0.07771,2.79,14.60
28701,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,797.0,0.07745,2.68,14.47
28702,351,Chine,2848,Lait - Excl Beurre,2012,animal,59.0,0.03300,3.27,3.09
28703,351,Chine,2848,Lait - Excl Beurre,2013,animal,59.0,0.03318,3.25,3.12
28704,351,Chine,2899,Miscellanees,2012,vegetal,0.0,NaN,0.00,0.01
28705,351,Chine,2899,Miscellanees,2013,vegetal,0.0,NaN,0.00,0.01

In [7]:
data_q16.to_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/dispo_alim.csv", index = False)

In [8]:
"""La clé primaire pour cette table serait Pays-Produit-Année"""

'La clé primaire pour cette table serait Pays-Produit-Année'

In [9]:
"""Question 17"""

'Question 17'

In [10]:
equilibre_prod = pd.read_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/all_q17.csv", encoding='utf-8')

equilibre_prod = equilibre_prod.drop(columns=['Code Année', 'Code Élément', 'Domaine', 'Code Domaine'])
equilibre_prod = equilibre_prod.pivot_table(
    index=['Code Produit', 'Produit', 'Code Pays', 'Pays', 'Année'],
    columns=['Élément'],
    values='Valeur')

equilibre_prod.columns = ['Alim_ani', 'Autres_utilisations', 'Dispo_int', 'Nourriture', 'Pertes', 'Semences', 'Transfo']

equilibre_prod = equilibre_prod.reset_index()

equilibre_prod.columns = ['code_produit', 'produit', 'code_pays', 'pays', 'annee', 'alim_ani', 'autres_utilisations', 'dispo_int', 'nourriture', 'pertes', 'semences', 'transfo']

equilibre_prod

,code_produit,produit,code_pays,pays,annee,alim_ani,autres_utilisations,dispo_int,nourriture,pertes,semences,transfo
0,2511,Blé,1,Arménie,2012,92.0,0.0,532.0,377.0,29.0,23.0,10.0
1,2511,Blé,1,Arménie,2013,93.0,0.0,554.0,389.0,32.0,30.0,10.0
2,2511,Blé,2,Afghanistan,2012,NaN,NaN,5884.0,4810.0,758.0,316.0,NaN
3,2511,Blé,2,Afghanistan,2013,NaN,NaN,5992.0,4895.0,775.0,322.0,NaN
4,2511,Blé,3,Albanie,2012,20.0,150.0,673.0,440.0,45.0,19.0,NaN
5,2511,Blé,3,Albanie,2013,18.0,130.0,650.0,440.0,44.0,18.0,NaN
6,2511,Blé,4,Algérie,2012,635.0,810.0,9462.0,7179.0,685.0,153.0,0.0
7,2511,Blé,4,Algérie,2013,545.0,820.0,9461.0,7270.0,672.0,153.0,0.0
8,2511,Blé,7,Angola,2012,NaN,NaN,858.0,837.0,21.0,0.0,0.0
9,2511,Blé,7,Angola,2013,NaN,NaN,898.0,874.0,23.0,0.0,0.0
10,2511,Blé,8,Antigua-et-Barbuda,2012,NaN,0.0,6.0,5.0,NaN,NaN,NaN
11,2511,Blé,8,Antigua-et-Barbuda,2013,NaN,1.0,7.0,6.0,NaN,NaN,NaN
12,2511,Blé,9,Argentine,2012,0.0,1.0,4849.0,4040.0,442.0,365.0,NaN
13,2511,Blé,9,Argentine,2013,0.0,19.0,5251.0,4273.0,424.0,534.0,NaN
14,2511,Blé,10,Australie,2012,3134.0,888.0,6665.0,1602.0,299.0,676.0,66.0
15,2511,Blé,10,Australie,2013,3200.0,920.0,6691.0,1645.0,229.0,631.0,66.0
16,2511,Blé,11,Autriche,2012,339.0,45.0,1178.0,689.0,32.0,54.0,18.0
17,2511,Blé,11,Autriche,2013,467.0,58.0,1320.0,689.0,40.0,55.0,11.0
18,2511,Blé,12,Bahamas,2012,NaN,13.0,25.0,12.0,NaN,NaN,NaN
19,2511,Blé,12,Bahamas,2013,NaN,14.0,29.0,15.0,NaN,NaN,NaN
20,2511,Blé,14,Barbade,2012,1.0,3.0,22.0,18.0,NaN,NaN,0.0
21,2511,Blé,14,Barbade,2013,1.0,3.0,23.0,19.0,NaN,NaN,0.0
22,2511,Blé,16,Bangladesh,2012,NaN,500.0,3357.0,2639.0,177.0,42.0,0.0
23,2511,Blé,16,Bangladesh,2013,NaN,500.0,3497.0,2736.0,221.0,41.0,0.0
24,2511,Blé,17,Bermudes,2012,NaN,2.0,6.0,4.0,NaN,NaN,NaN
25,2511,Blé,17,Bermudes,2013,NaN,3.0,7.0,4.0,NaN,NaN,NaN
26,2511,Blé,19,Bolivie (État plurinational de),2012,NaN,0.0,568.0,529.0,23.0,17.0,NaN
27,2511,Blé,19,Bolivie (État plurinational de),2013,NaN,0.0,583.0,533.0,31.0,19.0,NaN
28,2511,Blé,20,Botswana,2012,NaN,NaN,79.0,75.0,5.0,0.0,0.0
29,2511,Blé,20,Botswana,2013,NaN,NaN,84.0,77.0,7.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
30926,2848,Lait - Excl Beurre,233,Burkina Faso,2012,2.0,NaN,383.0,365.0,15.0,NaN,NaN
30927,2848,Lait - Excl Beurre,233,Burkina Faso,2013,3.0,NaN,530.0,505.0,22.0,NaN,NaN
30928,2848,Lait - Excl Beurre,234,Uruguay,2012,164.0,4.0,1053.0,739.0,145.0,NaN,NaN
30929,2848,Lait - Excl Beurre,234,Uruguay,2013,239.0,23.0,1139.0,717.0,160.0,NaN,NaN
30930,2848,Lait - Excl Beurre,235,Ouzbékistan,2012,3562.0,NaN,7344.0,3782.0,NaN,NaN,0.0
30931,2848,Lait - Excl Beurre,235,Ouzbékistan,2013,4125.0,NaN,7910.0,3785.0,NaN,NaN,0.0
30932,2848,Lait - Excl Beurre,236,Venezuela (République bolivarienne du),2012,NaN,48.0,4488.0,4409.0,35.0,NaN,NaN
30933,2848,Lait - Excl Beurre,236,Venezuela (République bolivarienne du),2013,NaN,42.0,3643.0,3582.0,33.0,NaN,NaN
30934,2848,Lait - Excl Beurre,237,Viet Nam,2012,NaN,NaN,1553.0,1541.0,13.0,NaN,NaN
30935,2848,Lait - Excl Beurre,237,Viet Nam,2013,NaN,NaN,1515.0,1500.0,15.0,NaN,NaN
30936,2848,Lait - Excl Beurre,238,Éthiopie,2012,18.0,0.0,4093.0,3957.0,122.0,NaN,NaN
30937,2848,Lait - Excl Beurre,238,Éthiopie,2013,18.0,0.0,4296.0,4153.0,129.0,NaN,NaN
30938,2848,Lait - Excl Beurre,244,Samoa,2012,0.0,0.0,9.0,9.0,0.0,NaN,NaN
30939,2848,Lait - Excl Beurre,244,Samoa,2013,0.0,0.0,10.0,10.0,0.0,NaN,NaN
30940,2848,Lait - Excl Beurre,249,Yémen,2012,NaN,25.0,1078.0,1050.0,15.0,NaN,NaN
30941,2848,Lait - Excl Beurre,249,Yémen,2013,NaN,7.0,1075.0,1073.0,15.0,NaN,NaN
30942,2848,Lait - Excl Beurre,251,Zambie,2012,3.0,NaN,136.0,129.0,4.0,NaN,NaN
30943,2848,Lait - Excl Beurre,251,Zambie,2013,5.0,NaN,150.0,141.0,4.0,NaN,NaN
30944,2848,Lait - Excl Beurre,255,Belgique,2012,496.0,175.0,3051.0,2526.0,NaN,NaN,4.0
30945,2848,Lait - Excl Beurre,255,Belgique,2013,885.0,165.0,3513.0,2623.0,NaN,NaN,0.0
30946,2848,Lait - Excl Beurre,256,Luxembourg,2012,21.0,0.0,162.0,141.0,NaN,NaN,NaN
30947,2848,Lait - Excl Beurre,256,Luxembourg,2013,21.0,2.0,158.0,135.0,NaN,NaN,NaN
30948,2848,Lait - Excl Beurre,272,Serbie,2012,49.0,NaN,1519.0,1439.0,31.0,NaN,NaN
30949,2848,Lait - Excl Beurre,272,Serbie,2013,74.0,NaN,1516.0,1413.0,30.0,NaN,NaN
30950,2848,Lait - Excl Beurre,273,Monténégro,2012,42.0,NaN,244.0,197.0,3.0,NaN,NaN
30951,2848,Lait - Excl Beurre,273,Monténégro,2013,43.0,NaN,265.0,217.0,4.0,NaN,NaN
30952,2848,Lait - Excl Beurre,276,Soudan,2012,NaN,0.0,5856.0,5856.0,NaN,NaN,0.0
30953,2848,Lait - Excl Beurre,276,Soudan,2013,NaN,0.0,5892.0,5892.0,NaN,NaN,0.0
30954,2848,Lait - Excl Beurre,351,Chine,2012,1627.0,44.0,49643.0,46461.0,1514.0,NaN,0.0
30955,2848,Lait - Excl Beurre,351,Chine,2013,1632.0,42.0,50117.0,47009.0,1433.0,NaN,0.0

In [11]:
equilibre_prod.to_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/equilibre_prod.csv", index = False)

In [12]:
"""La clé primaire serait Code_Produit-Code_pays-Année"""

'La clé primaire serait Code_Produit-Code_pays-Année'

In [13]:
"""Question 18"""

'Question 18'

In [14]:
sous_nutrition = pd.read_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/all_q18.csv", encoding='utf-8')

sous_nutrition = sous_nutrition.drop(columns = ['Code Domaine', 'Domaine', 'Code Élément'])

sous_nutrition = sous_nutrition.pivot_table(
    index = ['Code zone', 'Zone', 'Année'],
    columns = 'Élément',
    values = 'Valeur')

sous_nutrition = sous_nutrition.reset_index()

sous_nutrition.columns = ['Code Pays', 'Pays', 'Année', 'Nb_personnes']

sous_nutrition['Nb_personnes'] = sous_nutrition['Nb_personnes']*1000000

sous_nutrition.columns = ['code_pays', 'pays', 'annee', 'nb_personnes']

sous_nutrition

     code_pays         pays      annee  nb_personnes
0            1      Arménie  2011-2013      100000.0
1            1      Arménie  2012-2014      100000.0
2            1      Arménie  2013-2015      100000.0
3            1      Arménie  2014-2016      100000.0
4            1      Arménie  2015-2017      100000.0
5            2  Afghanistan  2011-2013     7200000.0
6            2  Afghanistan  2012-2014     8100000.0
7            2  Afghanistan  2013-2015     9000000.0
8            2  Afghanistan  2014-2016     9900000.0
9            2  Afghanistan  2015-2017    10500000.0
10           3      Albanie  2011-2013      200000.0
11           3      Albanie  2012-2014      200000.0
12           3      Albanie  2013-2015      200000.0
13           3      Albanie  2014-2016      200000.0
14           3      Albanie  2015-2017      200000.0
15           4      Algérie  2011-2013     1900000.0
16           4      Algérie  2012-2014     1800000.0
17           4      Algérie  2013-2015     1800000.0
18           4      Algérie  2014-2016     1900000.0
19           4      Algérie  2015-2017     1900000.0
20           7       Angola  2011-2013     8800000.0
21           7       Angola  2012-2014     8000000.0
22           7       Angola  2013-2015     7300000.0
23           7       Angola  2014-2016     6900000.0
24           7       Angola  2015-2017     6900000.0
25           9    Argentine  2011-2013     1600000.0
26           9    Argentine  2012-2014     1500000.0
27           9    Argentine  2013-2015     1500000.0
28           9    Argentine  2014-2016     1600000.0
29           9    Argentine  2015-2017     1700000.0
..         ...          ...        ...           ...
458        238     Éthiopie  2011-2013    26800000.0
459        238     Éthiopie  2012-2014    25500000.0
460        238     Éthiopie  2013-2015    24000000.0
461        238     Éthiopie  2014-2016    22800000.0
462        238     Éthiopie  2015-2017    21900000.0
463        249        Yémen  2011-2013     6500000.0
464        249        Yémen  2012-2014     7100000.0
465        249        Yémen  2013-2015     7900000.0
466        249        Yémen  2014-2016     8800000.0
467        249        Yémen  2015-2017     9500000.0
468        251       Zambie  2011-2013     7000000.0
469        251       Zambie  2012-2014     7000000.0
470        251       Zambie  2013-2015     7000000.0
471        251       Zambie  2014-2016     7100000.0
472        251       Zambie  2015-2017     7400000.0
473        272       Serbie  2011-2013      500000.0
474        272       Serbie  2012-2014      500000.0
475        272       Serbie  2013-2015      500000.0
476        272       Serbie  2014-2016      500000.0
477        272       Serbie  2015-2017      500000.0
478        276       Soudan  2011-2013     9200000.0
479        276       Soudan  2012-2014     9300000.0
480        276       Soudan  2013-2015     9500000.0
481        276       Soudan  2014-2016     9700000.0
482        276       Soudan  2015-2017    10000000.0
483        351        Chine  2011-2013   146200000.0
484        351        Chine  2012-2014   137300000.0
485        351        Chine  2013-2015   129700000.0
486        351        Chine  2014-2016   125600000.0
487        351        Chine  2015-2017   124500000.0

[488 rows x 4 columns]

In [15]:
sous_nutrition.to_csv("C:/Users/JulienPaulet/Desktop/Open_Classroom/P3_Realisez_une_etude_de_sante_publique/Donnees/Bilan_alimentaire/pour_sql/sous_nutrition.csv", index = False)

In [16]:
"""La clé primaire serait Pays-Année"""

'La clé primaire serait Pays-Année'